export const ADMIN_RESOURCES = [
  {
    key: "profiles",
    title: "Users (profiles)",
    table: "profiles",
    idCol: "id",
    columns: [
      "id",
      "role",
      "can_buy",
      "can_sell",
      "is_verified_company",
      "full_name",
      "company_name",
      "phone",
      "country",
      "created_at",
      "updated_at",
    ],
    editable: ["role", "can_buy", "can_sell", "is_verified_company", "full_name", "company_name", "phone", "country"],
  },
  {
    key: "rfqs",
    title: "RFQs",
    table: "rfqs",
    idCol: "id",
    columns: ["id", "buyer_id", "owner_id", "title", "description", "country", "budget_pi", "deadline", "status", "created_at"],
    editable: ["status", "deadline", "budget_pi", "title", "description", "country"],
  },
  {
    key: "rfq_offers",
    title: "RFQ Offers",
    table: "rfq_offers",
    idCol: "id",
    columns: ["id", "rfq_id", "owner_id", "price_pi", "message", "status", "created_at"],
    editable: ["status", "price_pi", "message"],
  },
  {
    key: "feature_flags",
    title: "Feature Flags",
    table: "feature_flags",
    idCol: "key",
    columns: ["key", "enabled", "note", "updated_at"],
    editable: ["enabled", "note"],
    pkIsText: true,
  },
  {
    key: "audit_log",
    title: "Audit Log",
    table: "audit_log",
    idCol: "id",
    columns: ["id", "actor_id", "action", "table_name", "row_id", "payload", "created_at"],
    editable: [], // read-only
    readOnly: true,
  },
];
